### ISSUE TITLE
I am not getting given_name returned

### ISSUE THREAD

**Issue by garybushey** [robisim74/Angular2SPAWebAPI#10]
I have switched the code to use an Azure SQL Database and I can register and login just fine however when I login I never seem to get the "given_name" returned.  I added the EntityFramework Core SQL driver and can see my accounts getting created correctly in the database but when I watch what happens when I login I only get the GUID, Name, and Role fields returned in the JSON.

This is working perfectly when using the SQLite file that comes with the project.

**Comment by robisim74** [comment]
In theory it should work with any db.
To get user data, this example uses IdentityServer _userinfo_ endpoint. This endpoint works as a black box: it only returns the data that are in the database as _claims_.
If the endpoint doesn't return any value, it could be a permissions problem of Azure: but in this case, you said that in response you see _sub_, _name_ and _role_, but not _given_name_. In order that the endpoint returns the _given_name_, when the user is created, the respective claims are also created:
```
           var claims = new List<Claim> {
                new Claim(type: JwtClaimTypes.GivenName, value: user.GivenName),
                new Claim(type: JwtClaimTypes.FamilyName, value: user.FamilyName),
            };
            await _userManager.AddClaimsAsync(user, claims);
```
and in the db I see the _AspNetUserClaims_ table populated:

![image](https://cloud.githubusercontent.com/assets/14012361/24820572/109b3418-1bea-11e7-8166-10acb9003a86.png)

However, if your configuration and the data in db are correct, you could avoid to use _userinfo_ endpoint. You are not forced to use it, and  simply you  could implement an API in the _Identity_ controller that returns the user data from the db.

**Comment by garybushey** [comment]
Thank you for your assistance.  With your help I was able to determine that I messed up when I created the tables in my Azure SQL environment and did not make any of the ID fields as Identity fields thereby causing errors when trying to insert values into them.  Everything is working fine now.
