### ISSUE TITLE
Is this the right way to do it?

### ISSUE THREAD

**Issue by leolorenzoluis** [robisim74/Angular2SPAWebAPI#14]
Hello, thanks for your sample I am able to understand further about such topic. I have a question whether I'm doing it right or wrong.

I am using your sample. However, the difference is the IdentityServer is hosted on its own. The SPA and APIs are hosted on the same server. (Probably separated soon but not now). 

Since it's using ROPC, I just get the access tokens with its default claims that I asked for. I may be doing something wrong or missing something, but I tried `ProfileService` etc just so to force it to spit out the custom claims when I access `connect/token`. However, it doesn't look like I am on the right path and based on my research. It suggested to let the client use `connect/userinfo` to get the information. That makes sense. However, my scenario is given the `User.Claims` from asp.net, I need to be able to know who you are besides giving me the id such as first name or last name. Currently what I'm doing is the following:

```
        var identityId = User.FindFirst("sub").Value;
        value.UserId = new Guid(identityId);
        var p = await _userManager.FindByIdAsync(identityId);
        var m = await _userManager.GetClaimsAsync(p);
```

Which works but I'm not sure if it's correct. I wanted to minimize the database calls if the client can just get the claims and pass it through the server. What do you think?

**Comment by robisim74** [comment]
Hi @leolorenzoluis,

to add custom claims to the access token, you can add them to the API Resources:

```
public static IEnumerable<ApiResource> GetApiResources()
{
    return new List<ApiResource>
        {
            new ApiResource("WebAPI" ) {
                UserClaims = { "role", "given_name" }
            }
        };
}
```
but then you have to decode the token on the client.

This project does not decode the access token on the client: https://github.com/robisim74/AngularSPAWebAPI/issues/3

So if you don't want to use the UserInfo endpoint, I think that creating a custom API to return values is the only way.

Greetings,
Roberto

**Comment by leolorenzoluis** [comment]
The claims are not stored in memory but in Database using asp default table Claims. The client doesnt need to decode the claims but the server hosting the SPA in order to save a trip to the database. If I access the token endpoint, how do I return it with the custom claims or tell IS that while its fetching for User id in database include the claims too when a token is created

**Comment by robisim74** [comment]
I'm closing this issue. For this kind of questions, please use StackOverflow. Greetings
