### ISSUE TITLE
Fix for AOT compilation and Lazy-Loaded modules

### ISSUE THREAD

**Issue by aalmajanob** [robisim74/Angular2SPAWebAPI#16]
Dear Roberto,

  How are you?

  I had to perform a little change over your original 'webpack.config.js' file in order to fix a problem which was causing an error when compile in AOT + LazyLoading Modules.

  The fix is just to remove the '/app' from the genDir:
    `'angular-router-loader?aot=true&genDir=aot/app' `
    to
` 'angular-router-loader?aot=true&genDir=aot'`

  Explanation:

  When we use a LazyLoaded module: https://angular.io/guide/ngmodule#lazy-loading-modules-with-the-router we need to include its relative path as 

`  { path: 'values', loadChildren: './values/values.module#ValuesModule' } `

and include within the files tag at 'tsconfig-aot.json':

```
  "files": [
    "app/app.module.ts",
    "app/values/values.module.ts",
    "app/main-aot.ts"
  ],
```

  If we do not perform this fix the AOT routes appears with a duplicate app like `'.../app/app/values/values.module...' `

  I thought you could maybe find it interesting to know in case you include Lazy Loading approach in the future.

Regards,
Andrés.

**Comment by robisim74** [comment]
Hi Andrés,

thank you so much for suggesting this fixing!

Next time feel free to do a pr (for fixing or new features): you are welcome!

Greetings,
Roberto

**Comment by aalmajanob** [comment]
Hi Roberto,

  I'm not really familirized with git. The best way to suggest any change in the future would be to use a pull request?

  It is neccesary first to fork "attach" this project within my local computer?

  I will check this point when I get some time in order to try to share some interesting functionalities I have developed :)

  Regards,
Andrés.

**Comment by robisim74** [comment]
If you are not familiar with git, I suggest using GitHub desktop: https://desktop.github.com/

Guide: https://help.github.com/desktop-beta/guides/

Step:
- Make the fork of the project on GitHub
- Create a branch in GitHub desktop
- Make the changes in VS
- Make the commit in GitHub desktop 
- Create the pull request in GitHub desktop

Do not worry: as long as you do your local trials, nothing can happen.

However, the suggestions are always welcome, with or without PR!

**Comment by aalmajanob** [comment]
Ok, thanks you for the info! I will check it when possible!

**Comment by robisim74** [comment]
I know, time is always a problem for all of us. Greetings
