### ISSUE TITLE
Refresh token

### ISSUE THREAD

**Issue by quanterion** [robisim74/Angular2SPAWebAPI#2]
Thank you for great sample! It is interesting to know how it is possible to implement refresh_token to use short-lived access tokens and update them using refresh_tokens, that can be revoked

**Comment by robisim74** [comment]
Hi,

you can use the _grant type_ of IdentityServer: [Refresh tokens](http://docs.identityserver.io/en/dev/topics/grant_types.html#refresh-tokens).

For revocation, you must instead use the revocation endpoint: `http://localhost:5000/connect/revocation`.

However, if I have time in the next few days, I'll try to integrate it in the application as an option, or I will insert it in a note.

Greetings

**Comment by robisim74** [comment]
Hi,

I've added the support for refresh token. Now a _refresh token_ is returned with the _access token_, and using the _getNewToken_ method of _AuthenticationService_ class you can request a new _access token_ for the user at the desired time.
I've also added methods to revoke token. For more details see the [explanation](https://github.com/robisim74/Angular2SPAWebAPI/blob/master/EXPLANATION.md).

Greetings

**Comment by quanterion** [comment]
Thank you for great addition!
