### ISSUE TITLE
Cannot get userinfo from userinfo endpoint

### ISSUE THREAD

**Issue by lamemmv** [robisim74/Angular2SPAWebAPI#20]
I can signin successful, get access_token, but do not have refresh_token.
When the site try to get userinfor via connect/userinfo. It always give 405 error

`Response for preflight has invalid HTTP status code 405`

What're my missing?
thanks

**Comment by robisim74** [comment]
Refresh token uses the _Token endpoint_ and not the _Userinfo endpoint_.

Are you trying to run this app as-is or your app?
