### ISSUE TITLE
ASP.NET Core 2

### ISSUE THREAD

**Issue by robisim74** [robisim74/Angular2SPAWebAPI#23]
Upgrade to ASP.NET Core 2 when _IdentityServer_ will be ready.

**Comment by xjose97x** [comment]
I believe IdentityServer is ready

**Comment by robisim74** [comment]
done

**Comment by aalmajanob** [comment]
Hello Roberto,

  How are you?

  Since I will probably need to perform this step also in the short future, I would like to ask you if there has been neccesary to do many important changes (regarding net core 2.0 and Identity Server new version).

  Does this update result in many breaking changes?

  Regards,
Andrés.

**Comment by robisim74** [comment]
Hi Andrés,

now that all packages have been updated, it's not difficult: basically you need to change:
- csproj: https://github.com/robisim74/AngularSPAWebAPI/blob/master/AngularSPAWebAPI/AngularSPAWebAPI.csproj
- the authentication middleware in `Startup.cs`:
  - https://github.com/robisim74/AngularSPAWebAPI/blob/master/AngularSPAWebAPI/Startup.cs#L81-L89
  - https://github.com/robisim74/AngularSPAWebAPI/blob/master/AngularSPAWebAPI/Startup.cs#L134
- the `Authorize` attribute into controllers: https://github.com/robisim74/AngularSPAWebAPI/blob/master/AngularSPAWebAPI/Controllers/ValuesController.cs#L13

For this project, I preferred starting from scratch because there were a lot of things that were no longer needed (ASP.NET Core 2 has simplified several things).

What seems to be the biggest problem is the publication: I had to clean all the dlls from the production, the nuget cache before compiling and ultimately raise the self-generated certicate.

**Comment by aalmajanob** [comment]
Hi Roberto,

  Thanks for your help, this will help me a lot when I need to perform this update! 

  Regards,
Andrés.
