### ISSUE TITLE
question about role claims

### ISSUE THREAD

**Issue by BahgatMashaly** [robisim74/Angular2SPAWebAPI#27]
Hello Dear,

i'm trying to use role claims , but it doesn't work 

first i created role claim by adding these lines of code after created roles
```
   var adminRole = await _roleManager.FindByNameAsync("administrator");
  await _roleManager.AddClaimAsync(adminRole, new Claim("my_claim_type", value: "my_claim_value"));
```

and in services.AddAuthorization    i added this line

`options.AddPolicy("my_policy", policy => policy.RequireClaim("my_claim_type", "my_claim_value")); `

then

```
 [HttpGet]
       // [Authorize(Policy = "my_policy")]
        [Authorize(AuthenticationSchemes = IdentityServerAuthenticationDefaults.AuthenticationScheme, Policy = "my_policy")]
        public IEnumerable<string> Get()
        {
            return new string[] { "value1", "value2" };
        }

```
please any help to solve this problem

**Comment by robisim74** [comment]
I removed Role Claims from the project with this commit: https://github.com/robisim74/AngularSPAWebAPI/commit/9e3e252bd49c285525f75d1a92d4372ea9d983bd

I removed them because they create duplicate roles: https://github.com/IdentityServer/IdentityServer4.AspNetIdentity/issues/23

Hope this helps.

Greetings

**Comment by BahgatMashaly** [comment]
@robisim74   many thanks for your fast reply,

is this means i can't use  user claims with role claims in identityserver4 ?  or i don't understand something

**Comment by BahgatMashaly** [comment]
@robisim74 many thanks for your fast reply

**Comment by BahgatMashaly** [comment]
i should add my_claim_type as the below code in Config.cs

  ```
public static IEnumerable<ApiResource> GetApiResources()
        {
            return new List<ApiResource>
            {
                new ApiResource("WebAPI" ) {
                    UserClaims = { "role","my_claim_type" }
                }
            };
        }

```
