### ISSUE TITLE
Using SqlServer Problem with "id" column

### ISSUE THREAD

**Issue by marcopicasso** [robisim74/Angular2SPAWebAPI#29]
Hi @robisim74 ,
i get this error message when i try to update the database:
"Id column in aspnetroles table is an invalid type for use as key column...."

how can i solve this?

thanks

**Comment by robisim74** [comment]
Hi @Shyroby,

I didn't see this error using SqlServer: are you running this project as-is? when you get this error?

**Comment by marcopicasso** [comment]
When i try to update db with the cli

**Comment by robisim74** [comment]
Please provide more information: which command are you running?

**Comment by marcopicasso** [comment]
dotnet ef database update

**Comment by robisim74** [comment]
Why you are running this command? The db is seeded when the app starts.

**Comment by marcopicasso** [comment]
Because i want to use a different db using ssms

**Comment by marcopicasso** [comment]
I try with sql query on ssms changing from "text" type to "integer" type id column and in this case the error gone....ps: i'm italian. We have to necessarily speak english on github?

**Comment by robisim74** [comment]
As in the README, to use another db, for example SqlServer:

- Edit in Startup.cs:
```
services.AddDbContext<ApplicationDbContext>(options =>
    options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
```

- Edit the connection string in _appsettings.json_ like this:
`Server=(localdb)\\mssqllocaldb;Database=IdentityDB;Trusted_Connection=True;MultipleActiveResultSets=true`

When the app starts, the db is seeded without problems.

Then if you changes the models, using EF Core migrations or SSMS, is not related to this project.

Greetings

**Comment by marcopicasso** [comment]
Ok, i will try again...thank you so mutch!

**Comment by senzacionale** [comment]
This is not enough, By default you not support MSSQL. So if you change DB you also need to remove default migration files.

Solution after changing DB:

Remove:

```
dotnet ef database update 0
dotnet ef migrations remove
```

Create:

`dotnet ef migrations add CreateIdentity -o Data/Migrations`
