### ISSUE TITLE
Can't deploy your project

### ISSUE THREAD

**Issue by yakeer** [robisim74/Angular2SPAWebAPI#34]
Hey,
First of all, thanks for the template,
It really helped me understand things out with IdentityServer and ASPNetCORE + Angular.

I'm facing an issue when trying to deploy to Azure Web App,
I'm getting error 500, and in the Web App logs I see that it cannot find the index.htm, and therefore it throws the error 500.

Did anyone else faced the same issue?
Maybe you've got a solution?

**Comment by robisim74** [comment]
@yakeer Try to verify these settings for serving static files in production:
- https://github.com/robisim74/AngularSPAWebAPI/blob/master/ClientApp/angular.json#L20-L21
- https://github.com/robisim74/AngularSPAWebAPI/blob/master/Startup.cs#L110-L120
- https://github.com/robisim74/AngularSPAWebAPI/blob/master/Startup.cs#L141-L150

**Comment by robisim74** [comment]
@yakeer Did you solve your problem? This project is currently deployed on Azure without any error.
