### ISSUE TITLE
Requires editing appsettings.json

### ISSUE THREAD

**Issue by wizofaus** [robisim74/Angular2SPAWebAPI#35]
The provided appsettings.json has a hard-coded path in the connection string that won't work on most developer machines.  If you modify to just be "Data Source=IdentityDB.sqlite" and specify that this file should be "Copy If Newer" it works out of the box for everyone.

**Comment by robisim74** [comment]
The connection string has been updated. _Copy if newer_ not always is necessary.

Thanks for the suggestion.

Greetings
