### ISSUE TITLE
error.json() is not a function when username/password incorrect

### ISSUE THREAD

**Issue by wizofaus** [robisim74/Angular2SPAWebAPI#36]
On entering incorrect credentials I get a javascript error, error.json is not a function.
If I change lines 40-42 of signin.ts as follows:

                if (error.error) {
                    switch (error.error.error) {
                        case 'invalid_grant':

It works as expected.  No idea why it's "error.error.error"!

**Comment by robisim74** [comment]
Thanks for reporting. There was still the error handling of the old _HttpModule_.

Fixed.

Greetings
