### ISSUE TITLE
Add refresh token logic

### ISSUE THREAD

**Issue by simeyla** [robisim74/Angular2SPAWebAPI#4]
This is a great project that really helped me after having looked at many other similar projects.

Would really appreciate if you could add some simple logic for the refresh token and how it fits into this architecture.

https://auth0.com/blog/refresh-tokens-what-are-they-and-when-to-use-them/

**Comment by robisim74** [comment]
Hi @simeyla,

I'm working on this new feature (#3) which will also include a strategy for the refresh token (a scheduler). I hope to publish it by this week.
I'll keep you up to date.

Greetings,

Roberto

**Comment by simeyla** [comment]
Thanks Roberto. I've been reading up more about AuthGuards and found what I think is a good solution that doesn't require a scheduler (although I realize a scheduler could improve performance of refresh ever so slightly):

I think I've considered most cases here. I'm still new to angular2 so if you see I've missed anything let me know.

**Solution:**

It turns out that AuthGuard can return a boolean, promise or Observable. 

In **AuthGuard.ts:**

It turns out AuthGuard can return a boolean, promise or Observable<boolean>.

So I return a false if there is no refresh token available, but if there is then it calls the authentication service to try to refresh the token. 

    public canActivate(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): boolean | Observable<boolean>
    {
        if (tokenNotExpired())
        {
           // Signed in alreday
           return true;
        }

        var obs = this.authenticationService.tryRefresh();

        if (typeof obs === 'boolean')
        {
            if (!obs)
            {
                this.redirectSignin(state);
            }

            return obs;
        }
        else
        { 
            obs.subscribe((refreshed) => 
            {
                alert('Token refreshed ' + refreshed);     // remove after testing

                if (!refreshed)
                {
                    // unable to refresh token
                    this.redirectSignin(state);
                }
            });
        }

        return obs;
    }

    public redirectSignin(state: RouterStateSnapshot)
    {
        // Stores the attempted URL for redirecting.
        let url: string = state.url;
        this.authenticationService.redirectUrl = url;

        // Not signed in so redirects to signin page.
        this.router.navigate(['/signin']);
    }


In **authentication.service.ts:**

Immediately return **false** if there is no refresh token, otherwise make an Http call to try to refresh the token. If it is successful then the observable is completed with true. This value is then handled by the AuthGuard.

It is important the observable calls **share()** because it is subscribed to by both angular internal code and my own code.

    /**
    * Tries to get a new token using refresh token.
    */
    public tryRefresh(): Observable<any> | boolean
    {
        let refreshToken: string = localStorage.getItem('refresh_token');

        if (refreshToken != null)
        {
            // Token endpoint & params.
            let tokenEndpoint: string = Config.TOKEN_ENDPOINT;

            let params: any = {
                client_id: Config.CLIENT_ID,
                grant_type: "refresh_token",
                refresh_token: refreshToken
            };

            // Encodes the parameters.
            let body: string = this.encodeParams(params);

            return this.http.post(tokenEndpoint, body, this.options)
                .map((res: Response) =>
                {
                    let body: any = res.json();

                    // Successful if there's an access token in the response.
                    if (typeof body.access_token !== 'undefined')
                    {
                        // Stores access token & refresh token.
                        this.store(body);

                        return true;
                    }
                    else
                    {
                        return false;
                    }
                })
                .share();
        }
        else
        {
            return false;
        }
    }

**Comment by simeyla** [comment]
I'm sure your solution will be more secure - and come with further explanation about overcoming tampering - but as a quick solution for me to be able to get my boss logged in this is working well for me now. Thanks again for a very helpful project.

**Comment by robisim74** [comment]
Thank you for sharing!

The scheduler is only one of the possible solutions regarding the refresh token. Everyone should implement the best solution for the own project.

**Comment by simeyla** [comment]
Found one big issue with my solution - if you switch routes before the expiration time then everything is fine, but if you leave the application sitting there to expire and don't change routes then you'll get issues.

So I'll wait for your complete solution - but for now this will allow my boss to see his long awaited report page !

**Comment by robisim74** [comment]
Remember that the refresh token is valid even if the access token has expired: so you can check if the response is a 401 and request a new access token.

**Comment by robisim74** [comment]
Hi @simeyla,

I added a strategy for the refresh token, through a scheduler.

I hope it helps.

Greetings,

Roberto

**Comment by simeyla** [comment]
Thank you :-) In the meantime I cheated and set my original token with a
long expiration. This will help a lot
